package com.lq.model;

import java.math.BigDecimal;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOME_USER.KEY_ID
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    private BigDecimal keyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOME_USER.USER_NAME
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOME_USER.USER_LONGIN_NAME
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    private String userLonginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOME_USER.USER_PASSWORD
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOME_USER.USER_SEX
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOME_USER.USER_CREATE_DATE
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    private String userCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOME_USER.USER_IS_ENABLED
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    private BigDecimal userIsEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOME_USER.USER_ICON_UPLOAD_NAME
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    private String userIconUploadName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOME_USER.USER_ICON_URL
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    private String userIconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOME_USER.USER_ICON_SIZE
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    private BigDecimal userIconSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOME_USER.KEY_ID
     *
     * @return the value of HOME_USER.KEY_ID
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public BigDecimal getKeyId() {
        return keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOME_USER.KEY_ID
     *
     * @param keyId the value for HOME_USER.KEY_ID
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public void setKeyId(BigDecimal keyId) {
        this.keyId = keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOME_USER.USER_NAME
     *
     * @return the value of HOME_USER.USER_NAME
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOME_USER.USER_NAME
     *
     * @param userName the value for HOME_USER.USER_NAME
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOME_USER.USER_LONGIN_NAME
     *
     * @return the value of HOME_USER.USER_LONGIN_NAME
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public String getUserLonginName() {
        return userLonginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOME_USER.USER_LONGIN_NAME
     *
     * @param userLonginName the value for HOME_USER.USER_LONGIN_NAME
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public void setUserLonginName(String userLonginName) {
        this.userLonginName = userLonginName == null ? null : userLonginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOME_USER.USER_PASSWORD
     *
     * @return the value of HOME_USER.USER_PASSWORD
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOME_USER.USER_PASSWORD
     *
     * @param userPassword the value for HOME_USER.USER_PASSWORD
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOME_USER.USER_SEX
     *
     * @return the value of HOME_USER.USER_SEX
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOME_USER.USER_SEX
     *
     * @param userSex the value for HOME_USER.USER_SEX
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOME_USER.USER_CREATE_DATE
     *
     * @return the value of HOME_USER.USER_CREATE_DATE
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public String getUserCreateDate() {
        return userCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOME_USER.USER_CREATE_DATE
     *
     * @param userCreateDate the value for HOME_USER.USER_CREATE_DATE
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public void setUserCreateDate(String userCreateDate) {
        this.userCreateDate = userCreateDate == null ? null : userCreateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOME_USER.USER_IS_ENABLED
     *
     * @return the value of HOME_USER.USER_IS_ENABLED
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public BigDecimal getUserIsEnabled() {
        return userIsEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOME_USER.USER_IS_ENABLED
     *
     * @param userIsEnabled the value for HOME_USER.USER_IS_ENABLED
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public void setUserIsEnabled(BigDecimal userIsEnabled) {
        this.userIsEnabled = userIsEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOME_USER.USER_ICON_UPLOAD_NAME
     *
     * @return the value of HOME_USER.USER_ICON_UPLOAD_NAME
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public String getUserIconUploadName() {
        return userIconUploadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOME_USER.USER_ICON_UPLOAD_NAME
     *
     * @param userIconUploadName the value for HOME_USER.USER_ICON_UPLOAD_NAME
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public void setUserIconUploadName(String userIconUploadName) {
        this.userIconUploadName = userIconUploadName == null ? null : userIconUploadName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOME_USER.USER_ICON_URL
     *
     * @return the value of HOME_USER.USER_ICON_URL
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public String getUserIconUrl() {
        return userIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOME_USER.USER_ICON_URL
     *
     * @param userIconUrl the value for HOME_USER.USER_ICON_URL
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public void setUserIconUrl(String userIconUrl) {
        this.userIconUrl = userIconUrl == null ? null : userIconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOME_USER.USER_ICON_SIZE
     *
     * @return the value of HOME_USER.USER_ICON_SIZE
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public BigDecimal getUserIconSize() {
        return userIconSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOME_USER.USER_ICON_SIZE
     *
     * @param userIconSize the value for HOME_USER.USER_ICON_SIZE
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    public void setUserIconSize(BigDecimal userIconSize) {
        this.userIconSize = userIconSize;
    }
}