package com.lq.service.system.interfaces;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import com.lq.common.base.IBaseCommonService;
import com.lq.model.UserInfo;

/**
 * 系统用户接口
 * @author Administrator
 * 2017-12-4 10:48:44
 */
public interface IUserInfoService extends IBaseCommonService<UserInfo>{
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOME_USER
	 * @mbggenerated  Tue Dec 05 16:12:04 CST 2017
	 */
	int deleteByPrimaryKey(BigDecimal keyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOME_USER
	 * @mbggenerated  Tue Dec 05 16:12:04 CST 2017
	 */
	int insert(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOME_USER
	 * @mbggenerated  Tue Dec 05 16:12:04 CST 2017
	 */
	int insertSelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOME_USER
	 * @mbggenerated  Tue Dec 05 16:12:04 CST 2017
	 */
	UserInfo selectByPrimaryKey(BigDecimal keyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOME_USER
	 * @mbggenerated  Tue Dec 05 16:12:04 CST 2017
	 */
	int updateByPrimaryKeySelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOME_USER
	 * @mbggenerated  Tue Dec 05 16:12:04 CST 2017
	 */
	int updateByPrimaryKey(UserInfo record);
	
	//上面的方法是自动生成的，需要其他手动添加
	
}
