package com.lq.repository;

import com.lq.common.base.IBaseMapper;
import com.lq.model.UserInfo;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

@Repository("userInfoMapper")
public interface UserInfoMapper extends IBaseMapper<UserInfo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOME_USER
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOME_USER
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOME_USER
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOME_USER
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    UserInfo selectByPrimaryKey(BigDecimal keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOME_USER
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOME_USER
     *
     * @mbggenerated Wed Dec 06 09:35:31 CST 2017
     */
    int updateByPrimaryKey(UserInfo record);
    
    
}